export { TIPOS_VIA } from './tipoVia.js'
import { aplicarModificaciones } from './tipoVia.js'

export const ALCALDIAS = [
  'Álvaro Obregón',
  'Azcapotzalco',
  'Benito Juárez',
  'Coyoacán',
  'Cuajimalpa de Morelos',
  'Cuauhtémoc',
  'Gustavo A. Madero',
  'Iztacalco',
  'Iztapalapa',
  'La Magdalena Contreras',
  'Miguel Hidalgo',
  'Milpa Alta',
  'Tláhuac',
  'Tlalpan',
  'Venustiano Carranza',
  'Xochimilco',
]

export const INTERVENCIONES = [
  { value: 'cruce-peatonal', label: 'Cruce Peatonal' },
  { value: 'ciclovia', label: 'Ciclovía' },
  { value: 'banquetas', label: 'Banquetas' },
  { value: 'peatonalizacion', label: 'Peatonalización de Calles' },
  { value: 'transporte-publico', label: 'Integración de Transporte Público' },
  { value: 'intersecciones', label: 'Intersecciones Viales' },
  { value: 'jardines-infiltracion', label: 'Jardines de Infiltración' },
  { value: 'estacionamiento', label: 'Estacionamiento Público en Vía' },
  { value: 'paradas-transporte', label: 'Paradas de Transporte Público' },
  { value: 'reduccion-carriles', label: 'Reducción/Aumento de Carriles' },
]

export const normasDB = {
  'cruce-peatonal': {
    nombre: 'Cruce Peatonal',
    descripcion: 'Zona designada para el cruce de peatones en intersecciones y puntos específicos de vialidades urbanas.',
    obligatorias: [
      {
        parametro: 'Ancho mínimo de cruce',
        valor: '3.0',
        unidad: 'm',
        fuente: 'RCDF Art. 77',
        detalle: 'Ancho libre mínimo en la zona de cruce peatonal en vías secundarias.',
      },
      {
        parametro: 'Franjas de señalización horizontal',
        valor: '30',
        unidad: 'cm',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Franjas blancas retroreflectantes de 30 cm de ancho tipo cebra, espaciadas 30 cm entre sí.',
      },
      {
        parametro: 'Rampas de accesibilidad',
        valor: 'Obligatoria en ambos extremos',
        unidad: '—',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Toda intersección debe contar con rampas para personas con discapacidad en ambos extremos del cruce.',
      },
      {
        parametro: 'Pendiente máxima de rampa',
        valor: '8',
        unidad: '%',
        fuente: 'RCDF Art. 79 / NOM-034',
        detalle: 'Pendiente longitudinal máxima de 8 % para rampas de accesibilidad; 6 % recomendado.',
      },
      {
        parametro: 'Señal vertical R-16',
        valor: 'Obligatoria en ambas aproximaciones',
        unidad: '—',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Señal de CRUCE PEATONAL (R-16) colocada en ambas aproximaciones del cruce.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Ancho recomendado de cruce',
        valor: '4.0',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Ancho recomendado para cruces en vías primarias con alto flujo peatonal.',
      },
      {
        parametro: 'Zona de espera peatonal',
        valor: '1.5',
        unidad: 'm (profundidad)',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Profundidad mínima de la zona de espera en banqueta previa al cruce, libre de obstáculos.',
      },
      {
        parametro: 'Fase peatonal exclusiva en semáforo',
        valor: '7',
        unidad: 's mínimo',
        fuente: 'Manual de Dispositivos SEDATU 2014',
        detalle: 'Tiempo mínimo de fase exclusiva peatonal en intersecciones semaforizadas principales.',
      },
      {
        parametro: 'Distancia libre de obstáculos',
        valor: '20',
        unidad: 'm de aproximación',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'La visibilidad del cruce no debe estar obstaculizada en al menos 20 m antes del cruce.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho óptimo de cruce',
        valor: '4.5',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'Ancho óptimo para alta demanda peatonal; 4.5 m permite el paso simultáneo de flujos bidireccionales.',
      },
      {
        parametro: 'Velocidad peatonal de diseño',
        valor: '1.0',
        unidad: 'm/s',
        fuente: 'NACTO / HCM 7th Ed.',
        detalle: 'Velocidad de diseño estándar; se usa 0.9 m/s para mayor inclusión de personas mayores.',
      },
      {
        parametro: 'Triángulo de visibilidad en esquina',
        valor: '2.0 × 2.0',
        unidad: 'm',
        fuente: 'CROW Design Manual',
        detalle: 'Triángulo libre de obstáculos en esquinas para garantizar visibilidad mutua entre peatón y conductor.',
      },
      {
        parametro: 'Iluminancia mínima en cruce',
        valor: '50',
        unidad: 'lux',
        fuente: 'ITDP Estándar de Infraestructura',
        detalle: 'Nivel de iluminancia promedio mínimo sobre la superficie del cruce durante horas nocturnas.',
      },
    ],
    chartData: [
      { label: 'RCDF (mín.)', value: 3.0, unit: 'm', color: '#d97706' },
      { label: 'Manual CDMX', value: 4.0, unit: 'm', color: '#3b82f6' },
      { label: 'NACTO', value: 4.5, unit: 'm', color: '#10b981' },
    ],
    chartTitle: 'Ancho de cruce peatonal (m) — comparativa',
  },

  'ciclovia': {
    nombre: 'Ciclovía',
    descripcion: 'Infraestructura ciclista segregada del tránsito vehicular para circulación segura de bicicletas en vía pública.',
    obligatorias: [
      {
        parametro: 'Ancho mínimo carril unidireccional',
        valor: '1.5',
        unidad: 'm',
        fuente: 'RCDF Art. 77 / Manual SCT',
        detalle: 'Ancho libre mínimo por carril de circulación ciclista en vía exclusiva unidireccional.',
      },
      {
        parametro: 'Señalización en pavimento',
        valor: 'Cada 50',
        unidad: 'm',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Marca de ciclopista (pictograma de bicicleta + flecha) en pintura retroreflectante cada 50 m.',
      },
      {
        parametro: 'Señal vertical de ciclopista',
        valor: 'En inicio, cruces y cambios de dirección',
        unidad: '—',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Señal vertical de ciclovía obligatoria al inicio y en cada cruce o cambio de alineación.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Ancho carril bidireccional',
        valor: '2.5',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Ancho mínimo para ciclovía bidireccional que permite cruce de dos ciclistas.',
      },
      {
        parametro: 'Separación de tráfico vehicular',
        valor: '0.5',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Anchura mínima de franja pintada o bordillo de separación entre el carril ciclista y el vehicular.',
      },
      {
        parametro: 'Velocidad de diseño',
        valor: '25',
        unidad: 'km/h',
        fuente: 'SEDATU Manual de Infraestructura Ciclista',
        detalle: 'Velocidad de diseño para ciclovías urbanas en zonas de velocidad moderada.',
      },
      {
        parametro: 'Pendiente longitudinal máxima',
        valor: '5',
        unidad: '%',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Pendiente máxima recomendada; se acepta hasta 8 % en tramos cortos menores a 50 m.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho mínimo carril unidireccional',
        valor: '1.8',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'Ancho mínimo recomendado por NACTO para carril ciclista unidireccional junto a tráfico.',
      },
      {
        parametro: 'Ancho bidireccional protegido',
        valor: '3.0–4.5',
        unidad: 'm',
        fuente: 'NACTO Protected Bike Lanes',
        detalle: 'Rango óptimo para ciclovía bidireccional con separación física del tráfico vehicular.',
      },
      {
        parametro: 'Buffer de protección (apertura de puertas)',
        valor: '0.75',
        unidad: 'm',
        fuente: 'ITDP Ciclociudades Manual B',
        detalle: 'Zona buffer mínima entre ciclovía y carril de estacionamiento vehicular.',
      },
      {
        parametro: 'Radio mínimo de curvatura a 25 km/h',
        valor: '10',
        unidad: 'm',
        fuente: 'CROW Design Manual for Bicycle Traffic',
        detalle: 'Radio de curvatura mínimo que garantiza estabilidad del ciclista a la velocidad de diseño.',
      },
    ],
    chartData: [
      { label: 'RCDF (mín.)', value: 1.5, unit: 'm', color: '#d97706' },
      { label: 'NACTO (mín.)', value: 1.8, unit: 'm', color: '#10b981' },
      { label: 'CROW (rec.)', value: 2.0, unit: 'm', color: '#8b5cf6' },
      { label: 'Manual CDMX (bid.)', value: 2.5, unit: 'm', color: '#3b82f6' },
    ],
    chartTitle: 'Ancho de carril ciclista (m) — comparativa',
  },

  'banquetas': {
    nombre: 'Banquetas',
    descripcion: 'Infraestructura peatonal de acera para circulación segura y accesible de peatones en vía pública.',
    obligatorias: [
      {
        parametro: 'Ancho mínimo zona libre peatonal',
        valor: '1.5',
        unidad: 'm',
        fuente: 'RCDF Art. 76',
        detalle: 'Ancho libre mínimo de paso peatonal sin obstáculos como postes, árboles o rampas.',
      },
      {
        parametro: 'Pendiente transversal máxima',
        valor: '2',
        unidad: '%',
        fuente: 'RCDF Art. 76 / NOM-034',
        detalle: 'Pendiente máxima en sentido transversal de la banqueta para garantizar accesibilidad universal.',
      },
      {
        parametro: 'Material de superficie',
        valor: 'Antiderrapante sin deformaciones > 2 cm',
        unidad: '—',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'La superficie debe ser antiderrapante y sin irregularidades mayores a 2 cm de altura.',
      },
      {
        parametro: 'Altura de guarnición',
        valor: '0.15',
        unidad: 'm',
        fuente: 'RCDF Art. 76',
        detalle: 'Altura estándar de guarnición de concreto en la unión entre banqueta y arroyo vehicular.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Ancho total banqueta (vía primaria)',
        valor: '3.0',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Ancho mínimo total incluyendo zona de equipamiento en vialidades primarias de CDMX.',
      },
      {
        parametro: 'Zona de equipamiento urbano',
        valor: '0.6',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Franja para postes, señales, mobiliario urbano y arbolado, adyacente al arroyo vehicular.',
      },
      {
        parametro: 'Cepa mínima para arbolado',
        valor: '1.5 × 1.5',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX / SEDATU',
        detalle: 'Dimensiones mínimas de cepa para árboles de sombra en banquetas de vías primarias.',
      },
      {
        parametro: 'Señalización podotáctil',
        valor: 'Obligatoria en cambios de nivel',
        unidad: '—',
        fuente: 'SEDATU / NOM-233-SSA1',
        detalle: 'Franja podotáctil de advertencia y guía para personas con discapacidad visual en banquetas.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho mínimo zona de paso',
        valor: '2.4',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'Zona peatonal libre de obstáculos; 1.8 m absoluto mínimo, 2.4 m recomendado.',
      },
      {
        parametro: 'Buffer de equipamiento recomendado',
        valor: '0.9–1.8',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'Zona entre calzada y zona peatonal para mobiliario, arbolado y ciclovía.',
      },
      {
        parametro: 'Árbol de sombra cada',
        valor: '6–9',
        unidad: 'm',
        fuente: 'ITDP Guía de Espacio Público',
        detalle: 'Espaciado entre árboles de sombra para cobertura efectiva del corredor peatonal.',
      },
    ],
    chartData: [
      { label: 'RCDF (zona libre)', value: 1.5, unit: 'm', color: '#d97706' },
      { label: 'NACTO (recom.)', value: 2.4, unit: 'm', color: '#10b981' },
      { label: 'Manual CDMX (total)', value: 3.0, unit: 'm', color: '#3b82f6' },
    ],
    chartTitle: 'Ancho de banqueta / zona peatonal (m) — comparativa',
  },

  'peatonalizacion': {
    nombre: 'Peatonalización de Calles',
    descripcion: 'Transformación de vialidades vehiculares en espacios predominantemente o exclusivamente peatonales.',
    obligatorias: [
      {
        parametro: 'Paso libre mínimo continuo',
        valor: '3.0',
        unidad: 'm',
        fuente: 'RCDF Art. 76',
        detalle: 'Ancho mínimo de paso libre sin obstáculos a lo largo de toda la calle peatonalizada.',
      },
      {
        parametro: 'Acceso para vehículos de emergencia',
        valor: 'Garantizado (3.0 m)',
        unidad: 'm',
        fuente: 'RCDF / Ley de Protección Civil CDMX',
        detalle: 'Toda calle peatonalizada debe permitir el acceso de ambulancias y bomberos.',
      },
      {
        parametro: 'Señalización de restricción vehicular',
        valor: 'Obligatoria en cada acceso',
        unidad: '—',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Señal de calle peatonal y restricción vehicular al inicio de cada acceso a la zona.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Superficie peatonal mínima',
        valor: '50',
        unidad: '% de la sección',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Al menos el 50 % de la sección transversal debe destinarse a circulación peatonal.',
      },
      {
        parametro: 'Frecuencia de arbolado',
        valor: 'Cada 6',
        unidad: 'm',
        fuente: 'SEDATU / Manual Calles CDMX',
        detalle: 'Plantación de árboles cada 6 m para provisión de sombra en zonas peatonalizadas.',
      },
      {
        parametro: 'Superficie permeable',
        valor: '30',
        unidad: '% mínimo',
        fuente: 'SEDATU / Normas Ambientales CDMX',
        detalle: 'Mínimo 30 % de la superficie debe ser permeable o verde para gestión de aguas pluviales.',
      },
      {
        parametro: 'Iluminación promedio mínima',
        valor: '20',
        unidad: 'lux',
        fuente: 'NOM-013-ENER / Manual Calles CDMX',
        detalle: 'Nivel de iluminancia promedio mínimo en la superficie de calles peatonalizadas.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho zona peatonal activa',
        valor: '4.5',
        unidad: 'm mínimo',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'Ancho mínimo de la zona de tránsito activo en calles peatonalizadas de alta demanda.',
      },
      {
        parametro: 'Nodos de actividad urbana',
        valor: 'Cada ~15',
        unidad: 'm',
        fuente: 'ITDP Guía de Espacio Público',
        detalle: 'Bancas, fuentes o arte urbano cada ~15 m para generar vida urbana activa en la calle.',
      },
      {
        parametro: 'Superficie permeable recomendada',
        valor: '30',
        unidad: '% mínimo',
        fuente: 'CROW Design Manual',
        detalle: 'Proporción mínima de superficie permeable para gestión de agua pluvial en sitio.',
      },
    ],
    chartData: [
      { label: 'RCDF (paso mín.)', value: 3.0, unit: 'm', color: '#d97706' },
      { label: 'Manual CDMX', value: 4.0, unit: 'm', color: '#3b82f6' },
      { label: 'NACTO (activo)', value: 4.5, unit: 'm', color: '#10b981' },
    ],
    chartTitle: 'Ancho de zona peatonal (m) — comparativa',
  },

  'transporte-publico': {
    nombre: 'Integración de Transporte Público',
    descripcion: 'Diseño de infraestructura para integración modal y accesibilidad del transporte público colectivo.',
    obligatorias: [
      {
        parametro: 'Accesibilidad universal en paradas',
        valor: 'Obligatoria',
        unidad: '—',
        fuente: 'NOM-233-SSA1-2003',
        detalle: 'Todas las paradas deben tener rampa, señalización braille y piso podotáctil.',
      },
      {
        parametro: 'Radio máximo de cobertura de parada',
        valor: '400',
        unidad: 'm',
        fuente: 'RCDF / Programa Movilidad CDMX',
        detalle: 'Radio máximo de cobertura peatonal hacia paradas del sistema de transporte público.',
      },
      {
        parametro: 'Señalización de ruta en parada',
        valor: 'Obligatoria',
        unidad: '—',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Identificación de rutas, destinos y frecuencias obligatoria en todas las paradas.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Separación entre paradas',
        valor: '300–500',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Distancia entre paradas en zona urbana densa; hasta 800 m en zonas de baja densidad.',
      },
      {
        parametro: 'Integración tarifaria multimodal',
        valor: 'Recomendada',
        unidad: '—',
        fuente: 'SEDATU Plan de Movilidad 2019',
        detalle: 'Sistema unificado de pago con transbordos gratuitos o subsidiados entre modos.',
      },
      {
        parametro: 'Área de intercambio modal',
        valor: '50',
        unidad: 'm² mínimo',
        fuente: 'Manual de Calles CDMX / SEDATU',
        detalle: 'Superficie mínima en nodos de alta confluencia de rutas de transporte.',
      },
    ],
    internacionales: [
      {
        parametro: 'Frecuencia máxima hora pico',
        valor: '10',
        unidad: 'min entre unidades',
        fuente: 'ITDP BRT Standard 2016',
        detalle: 'Frecuencia máxima de paso aceptable en hora pico para un servicio de calidad.',
      },
      {
        parametro: 'Radio de cobertura peatonal',
        valor: '500',
        unidad: 'm',
        fuente: 'NACTO Transit Street Design Guide',
        detalle: 'Radio de cobertura peatonal estándar para paradas de BRT y líneas troncales.',
      },
      {
        parametro: 'Desnivel máx. plataforma-vehículo',
        valor: '50',
        unidad: 'mm',
        fuente: 'CROW ASVV',
        detalle: 'Desnivel máximo entre plataforma de parada y piso del vehículo para acceso sin asistencia.',
      },
    ],
    chartData: [
      { label: 'RCDF (cobertura)', value: 400, unit: 'm', color: '#d97706' },
      { label: 'Manual CDMX (sep. mín.)', value: 300, unit: 'm', color: '#3b82f6' },
      { label: 'NACTO (cobertura)', value: 500, unit: 'm', color: '#10b981' },
    ],
    chartTitle: 'Radio de cobertura / separación de paradas (m) — comparativa',
  },

  'intersecciones': {
    nombre: 'Intersecciones Viales',
    descripcion: 'Diseño de puntos de confluencia entre vialidades para mayor seguridad peatonal, ciclista y vehicular.',
    obligatorias: [
      {
        parametro: 'Radio de giro máximo en esquina',
        valor: '6.0',
        unidad: 'm',
        fuente: 'RCDF / Manual SCT Vialidades Urbanas',
        detalle: 'Radio máximo de curvatura en esquinas para limitar la velocidad de giro de vehículos.',
      },
      {
        parametro: 'Triángulo de visibilidad libre',
        valor: '30 × 30',
        unidad: 'm',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Triángulo libre de obstáculos en aproximaciones a intersecciones no semaforizadas.',
      },
      {
        parametro: 'Señalización de prioridad',
        valor: 'ALTO (R-1) o CEDA (R-2)',
        unidad: '—',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Señal de prioridad vial obligatoria en toda intersección no semaforizada.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Radio de giro recomendado',
        valor: '4.0–6.0',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Rango de radio de curvatura según jerarquía vial; menor radio aumenta protección peatonal.',
      },
      {
        parametro: 'Ancho mínimo isla de refugio peatonal',
        valor: '1.8',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Ancho mínimo de isla de refugio peatonal en cruces de vialidades de 4 o más carriles.',
      },
      {
        parametro: 'Longitud carril de giro exclusivo',
        valor: '40',
        unidad: 'm mínimo',
        fuente: 'SEDATU Manual de Vialidades 2019',
        detalle: 'Longitud mínima de carril exclusivo de giro en intersecciones principales.',
      },
    ],
    internacionales: [
      {
        parametro: 'Radio de giro óptimo (peatonal)',
        valor: '3.0–4.5',
        unidad: 'm',
        fuente: 'NACTO Intersection Design Guide',
        detalle: 'Radio óptimo para reducir velocidades de giro y aumentar seguridad de peatones.',
      },
      {
        parametro: 'Ancho mínimo isla de refugio',
        valor: '2.0',
        unidad: 'm',
        fuente: 'NACTO Intersection Design Guide',
        detalle: 'Ancho mínimo de isla de refugio peatonal recomendado para seguridad en cruces amplios.',
      },
      {
        parametro: 'Avance de línea de parada ciclista',
        valor: '1.0–2.0',
        unidad: 'm',
        fuente: 'ITDP Ciclociudades',
        detalle: 'Avance de la línea de parada para ciclistas respecto a vehículos en semáforos.',
      },
      {
        parametro: 'Velocidad objetivo en giro',
        valor: '15–25',
        unidad: 'km/h',
        fuente: 'CROW Design Manual',
        detalle: 'Velocidad de diseño en giro para garantizar seguridad peatonal y ciclista.',
      },
    ],
    chartData: [
      { label: 'Manual SCT (máx.)', value: 6.0, unit: 'm', color: '#d97706' },
      { label: 'Manual CDMX (rec.)', value: 4.0, unit: 'm', color: '#3b82f6' },
      { label: 'NACTO (óptimo)', value: 3.5, unit: 'm', color: '#10b981' },
      { label: 'CROW', value: 4.0, unit: 'm', color: '#8b5cf6' },
    ],
    chartTitle: 'Radio de giro en esquina (m) — menor valor = mayor seguridad peatonal',
  },

  'jardines-infiltracion': {
    nombre: 'Jardines de Infiltración',
    descripcion: 'Infraestructura verde para captación y filtración natural de agua pluvial en vía pública.',
    obligatorias: [
      {
        parametro: 'Pendiente máxima de la superficie',
        valor: '5',
        unidad: '%',
        fuente: 'RCDF / NOM-CONAGUA',
        detalle: 'Pendiente máxima de la superficie del jardín para garantizar captación uniforme de agua.',
      },
      {
        parametro: 'Distancia mínima a cimentaciones',
        valor: '3.0',
        unidad: 'm',
        fuente: 'RCDF Art. 169',
        detalle: 'Separación mínima entre el borde del jardín y cualquier cimentación adyacente.',
      },
      {
        parametro: 'Desborde hacia drenaje convencional',
        valor: 'Obligatorio',
        unidad: '—',
        fuente: 'RCDF / Normas SACMEX',
        detalle: 'El jardín debe contar con desborde conectado al drenaje para eventos extremos.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Capacidad de infiltración mínima',
        valor: '25',
        unidad: 'mm/hr',
        fuente: 'SEDATU Manual de Infraestructura Verde 2020',
        detalle: 'Tasa de infiltración mínima del sustrato medida in situ con permeámetro de campo.',
      },
      {
        parametro: 'Profundidad de sustrato drenante',
        valor: '0.3–0.6',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX / SEDATU',
        detalle: 'Profundidad de mezcla de sustrato de alta permeabilidad en el jardín de infiltración.',
      },
      {
        parametro: 'Proporción de especies nativas',
        valor: '70',
        unidad: '% mínimo',
        fuente: 'SEDATU / CONABIO',
        detalle: 'Mínimo 70 % de la paleta vegetal debe ser de especies nativas o adaptadas al clima local.',
      },
      {
        parametro: 'Relación área jardín/cuenca aportante',
        valor: '1:20',
        unidad: 'ratio',
        fuente: 'SEDATU Manual de Infraestructura Verde',
        detalle: 'Relación mínima entre área del jardín y área de cuenca para diseño efectivo.',
      },
    ],
    internacionales: [
      {
        parametro: 'Relación área/cuenca recomendada',
        valor: '1:20–1:30',
        unidad: 'ratio',
        fuente: 'NACTO Urban Street Stormwater Guide',
        detalle: 'Rango óptimo de relación jardín/cuenca para manejo efectivo de aguas pluviales.',
      },
      {
        parametro: 'Período de retorno de diseño',
        valor: '10',
        unidad: 'años',
        fuente: 'CROW Design Manual',
        detalle: 'Período de retorno de lluvia de diseño para dimensionamiento de la capacidad del jardín.',
      },
      {
        parametro: 'Tiempo máximo de retención',
        valor: '24–48',
        unidad: 'horas',
        fuente: 'ITDP / EPA Stormwater Guide',
        detalle: 'Tiempo máximo de retención del agua antes de infiltrarse o desbordar al drenaje.',
      },
    ],
    chartData: [
      { label: 'Infiltración mín. (SEDATU)', value: 25, unit: 'mm/hr', color: '#d97706' },
      { label: 'Infiltración rec. (CROW)', value: 50, unit: 'mm/hr', color: '#8b5cf6' },
      { label: 'Infiltración ópt. (NACTO)', value: 75, unit: 'mm/hr', color: '#10b981' },
    ],
    chartTitle: 'Tasa de infiltración recomendada (mm/hr) — comparativa',
  },

  'estacionamiento': {
    nombre: 'Estacionamiento Público en Vía',
    descripcion: 'Diseño y regulación de cajones de estacionamiento sobre el arroyo vehicular o banqueta.',
    obligatorias: [
      {
        parametro: 'Cajón perpendicular (ancho × largo)',
        valor: '2.5 × 5.0',
        unidad: 'm',
        fuente: 'RCDF Art. 83',
        detalle: 'Dimensiones mínimas de cajón en ángulo de 90° respecto a la banqueta.',
      },
      {
        parametro: 'Cajón paralelo (ancho × largo)',
        valor: '2.2 × 6.0',
        unidad: 'm',
        fuente: 'RCDF Art. 83',
        detalle: 'Dimensiones mínimas de cajón de estacionamiento paralelo a la banqueta.',
      },
      {
        parametro: 'Cajón accesible (ancho × largo)',
        valor: '3.8 × 5.0',
        unidad: 'm',
        fuente: 'RCDF Art. 83 / NOM-233',
        detalle: 'Dimensiones del cajón accesible para personas con discapacidad; mínimo 2 % del total.',
      },
      {
        parametro: 'Proporción cajones accesibles',
        valor: '2',
        unidad: '% del total (mín. 1)',
        fuente: 'RCDF / Ley de Accesibilidad CDMX',
        detalle: 'Mínimo 2 % de cajones accesibles, marcados y adyacentes a la banqueta.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Restricción en vialidades primarias',
        valor: 'Prohibido',
        unidad: '—',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Estacionamiento en vía pública prohibido en vialidades primarias y arteriales de CDMX.',
      },
      {
        parametro: 'Separación de banqueta (guarnición)',
        valor: '0.15',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Altura de guarnición que separa los cajones de estacionamiento de la banqueta.',
      },
      {
        parametro: 'Señalización vertical',
        valor: 'Serie E-27 a E-29',
        unidad: '—',
        fuente: 'Manual de Dispositivos SEDATU',
        detalle: 'Señales de estacionamiento, restricción y zona de carga y descarga según norma SEDATU.',
      },
    ],
    internacionales: [
      {
        parametro: 'Buffer de protección ciclista',
        valor: '0.5',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'Zona de amortiguamiento entre cajones y ciclovía adyacente para apertura segura de puertas.',
      },
      {
        parametro: 'Reducción máx. en zonas peatonales',
        valor: '20',
        unidad: '% de cajones actuales',
        fuente: 'ITDP Guía de Estacionamiento',
        detalle: 'Reducción máxima recomendada de cajones en vía en áreas de alta peatonalización.',
      },
      {
        parametro: 'Límite de carriles con estacionamiento',
        valor: '1',
        unidad: 'carril en vía < 4 carriles',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'En vialidades con menos de 4 carriles el estacionamiento en vía no debe ocupar más de 1.',
      },
    ],
    chartData: [
      { label: 'Cajón paralelo (ancho)', value: 2.2, unit: 'm', color: '#3b82f6' },
      { label: 'Cajón perpendicular (ancho)', value: 2.5, unit: 'm', color: '#d97706' },
      { label: 'Cajón accesible (ancho)', value: 3.8, unit: 'm', color: '#10b981' },
    ],
    chartTitle: 'Ancho de cajones de estacionamiento (m) — comparativa',
  },

  'paradas-transporte': {
    nombre: 'Paradas de Transporte Público',
    descripcion: 'Diseño de paradas, bahías y refugios para usuarios del transporte público colectivo urbano.',
    obligatorias: [
      {
        parametro: 'Longitud mínima de bahía',
        valor: '18',
        unidad: 'm',
        fuente: 'RCDF / Manual SCT',
        detalle: 'Longitud mínima de bahía de parada para autobús urbano estándar de 12 m.',
      },
      {
        parametro: 'Cubierta en rutas de alta demanda',
        valor: 'Obligatoria (>100 usuarios/hr)',
        unidad: '—',
        fuente: 'NOM-233-SSA1-2003',
        detalle: 'Cubierta o refugio obligatorio en paradas con demanda mayor a 100 usuarios por hora.',
      },
      {
        parametro: 'Accesibilidad en parada',
        valor: 'Rampa + braille + podotáctil',
        unidad: '—',
        fuente: 'NOM-233-SSA1-2003',
        detalle: 'Rampa de acceso, señalización braille y piso podotáctil obligatorios en todas las paradas.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Distancia entre paradas',
        valor: '300–500',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Separación recomendada entre paradas en zona urbana densa; hasta 800 m en periferia.',
      },
      {
        parametro: 'Área de espera por usuario',
        valor: '2',
        unidad: 'm² por usuario (hora pico)',
        fuente: 'SEDATU Manual de Paradas 2020',
        detalle: 'Superficie de área de espera techada calculada para la demanda de la hora de máxima afluencia.',
      },
      {
        parametro: 'Información de rutas y horarios',
        valor: 'Obligatoria',
        unidad: '—',
        fuente: 'Manual de Calles CDMX / SEDATU',
        detalle: 'Mapa de red, horarios y tiempo de espera deben ser visibles en todas las paradas.',
      },
      {
        parametro: 'Iluminación en área de espera',
        valor: '50',
        unidad: 'lux mínimo',
        fuente: 'NOM-013-ENER / Manual SEDATU',
        detalle: 'Nivel de iluminancia mínimo para seguridad nocturna en el área de espera de la parada.',
      },
    ],
    internacionales: [
      {
        parametro: 'Desnivel máx. plataforma-vehículo',
        valor: '25',
        unidad: 'mm',
        fuente: 'CROW ASVV',
        detalle: 'Desnivel máximo entre plataforma de parada y piso del vehículo para acceso sin asistencia.',
      },
      {
        parametro: 'Longitud de plataforma BRT',
        valor: '15',
        unidad: 'm + zona buffer',
        fuente: 'NACTO Transit Street Design Guide',
        detalle: 'Longitud de plataforma de parada BRT más zona de amortiguamiento en los extremos.',
      },
      {
        parametro: 'Iluminancia mínima área espera',
        valor: '20',
        unidad: 'lux',
        fuente: 'ITDP BRT Standard',
        detalle: 'Nivel de iluminancia mínimo en área de espera según estándar ITDP para BRT de calidad básica.',
      },
    ],
    chartData: [
      { label: 'Plataforma NACTO (long.)', value: 15, unit: 'm', color: '#10b981' },
      { label: 'Bahía mín. RCDF (long.)', value: 18, unit: 'm', color: '#d97706' },
      { label: 'Sep. paradas mín. (CDMX)', value: 300, unit: 'm', color: '#3b82f6' },
    ],
    chartTitle: 'Longitud de bahía / plataforma de paradas (m) — comparativa',
  },

  'reduccion-carriles': {
    nombre: 'Reducción/Aumento de Carriles',
    descripcion: 'Modificación de la sección transversal vial mediante la reducción o adición de carriles de circulación.',
    obligatorias: [
      {
        parametro: 'Ancho mínimo de carril urbano',
        valor: '3.0',
        unidad: 'm',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Ancho mínimo de carril en vialidades urbanas; 3.5 m en vías primarias de alta velocidad.',
      },
      {
        parametro: 'Longitud mínima de transición',
        valor: '60',
        unidad: 'm (a 50 km/h)',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Longitud mínima de zona de transición al reducir o ampliar carriles a 50 km/h de velocidad diseño.',
      },
      {
        parametro: 'Señalización de zona de transición',
        valor: 'Delineadores + marcas viales + señales preventivas',
        unidad: '—',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Señalización completa obligatoria en toda zona de reducción o ampliación de carriles.',
      },
      {
        parametro: 'Línea central doble continua',
        valor: '10',
        unidad: 'cm ancho, color amarillo',
        fuente: 'NOM-034-SCT2-2011',
        detalle: 'Línea central doble continua amarilla de 10 cm de ancho en zonas de reducción de carriles.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Ancho de carril recomendado',
        valor: '3.0–3.5',
        unidad: 'm',
        fuente: 'Manual de Calles CDMX 2019',
        detalle: 'Rango óptimo en vialidades urbanas secundarias y primarias de CDMX.',
      },
      {
        parametro: 'Longitud carril de aceleración',
        valor: '60–80',
        unidad: 'm',
        fuente: 'SEDATU Manual de Vialidades',
        detalle: 'Longitud de carril de aceleración en incorporaciones a vialidades principales.',
      },
      {
        parametro: 'Velocidad de diseño en transición',
        valor: '50',
        unidad: 'km/h',
        fuente: 'Manual de Calles CDMX / SEDATU',
        detalle: 'Velocidad de diseño estándar para zonas de transición de carriles en vialidades urbanas.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho mínimo carril con ciclovía',
        valor: '3.0',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'Ancho mínimo de carril vehicular adyacente a ciclovía para garantizar seguridad.',
      },
      {
        parametro: 'Configuración "Road Diet" óptima',
        valor: '4→3 carriles',
        unidad: 'configuración',
        fuente: 'NACTO Urban Street Design Guide',
        detalle: 'Conversión de 4 a 3 carriles con carril central de giro; mejora seguridad vial y habilita ciclovía.',
      },
      {
        parametro: 'Reducción de accidentes con road diet',
        valor: '19–47',
        unidad: '% reducción',
        fuente: 'ITDP / FHWA Road Diet Studies',
        detalle: 'Rango documentado de reducción de accidentes en estudios de road diet en México y EE.UU.',
      },
    ],
    chartData: [
      { label: 'NOM-034 (mín.)', value: 3.0, unit: 'm', color: '#d97706' },
      { label: 'NACTO (con ciclovía)', value: 3.0, unit: 'm', color: '#10b981' },
      { label: 'Manual CDMX (rec.)', value: 3.25, unit: 'm', color: '#3b82f6' },
      { label: 'NOM-034 (vía primaria)', value: 3.5, unit: 'm', color: '#8b5cf6' },
    ],
    chartTitle: 'Ancho de carril vehicular (m) — comparativa de estándares',
  },
}

export function getNormas(intervencion) {
  return normasDB[intervencion] || null
}

export function getNormasConTipoVia(intervencion, tipoVia) {
  const base = normasDB[intervencion]
  if (!base) return null
  return aplicarModificaciones(base, intervencion, tipoVia)
}
