export { TIPOS_VIA } from './tipoVia.js'
import { aplicarModificaciones } from './tipoVia.js'

export const ALCALDIAS = [
  'Álvaro Obregón',
  'Azcapotzalco',
  'Benito Juárez',
  'Coyoacán',
  'Cuajimalpa de Morelos',
  'Cuauhtémoc',
  'Gustavo A. Madero',
  'Iztacalco',
  'Iztapalapa',
  'La Magdalena Contreras',
  'Miguel Hidalgo',
  'Milpa Alta',
  'Tláhuac',
  'Tlalpan',
  'Venustiano Carranza',
  'Xochimilco',
]

export const INTERVENCIONES = [
  { value: 'cruce-peatonal', label: 'Cruce Peatonal' },
  { value: 'ciclovia', label: 'Ciclovía' },
  { value: 'banquetas', label: 'Banquetas' },
  { value: 'peatonalizacion', label: 'Peatonalización de Calles' },
  { value: 'transporte-publico', label: 'Integración de Transporte Público' },
  { value: 'intersecciones', label: 'Intersecciones Viales' },
  { value: 'jardines-infiltracion', label: 'Jardines de Infiltración' },
  { value: 'estacionamiento', label: 'Estacionamiento Público en Vía' },
  { value: 'paradas-transporte', label: 'Paradas de Transporte Público' },
  { value: 'reduccion-carriles', label: 'Reducción/Aumento de Carriles' },
]

export const normasDB = {
  'cruce-peatonal': {
    nombre: 'Cruce Peatonal',
    descripcion: 'Zona designada para el cruce de peatones en intersecciones y puntos específicos de vialidades urbanas.',
    requiereEspecialista: false,
    especialistas: [],
    nota: '',
    obligatorias: [
      {
        parametro: 'Ancho mínimo de cruce',
        valor: '3.0',
        unidad: 'm',
        fuente: 'RCDF Art. 77',
        referencia: 'Art. 77, Título Quinto',
        detalle: 'Ancho libre mínimo en la zona de cruce peatonal en vías secundarias.',
      },
      {
        parametro: 'Franjas de señalización horizontal',
        valor: '30',
        unidad: 'cm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.9 (M-7)',
        detalle: 'Franjas blancas retroreflectantes de 30 cm de ancho tipo cebra, espaciadas 30 cm entre sí.',
      },
      {
        parametro: 'Rampas de accesibilidad',
        valor: 'Obligatoria en ambos extremos',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Ver Sección 5 o 6 según aplique',
        detalle: 'Toda intersección debe contar con rampas para personas con discapacidad en ambos extremos del cruce.',
      },
      {
        parametro: 'Pendiente máxima de rampa',
        valor: '8',
        unidad: '%',
        fuente: 'RCDF Art. 79 / NOM-034',
        referencia: 'Art. 79, Título Quinto',
        detalle: 'Pendiente longitudinal máxima de 8 % para rampas de accesibilidad; 6 % recomendado.',
      },
      {
        parametro: 'Señal vertical R-16',
        valor: 'Obligatoria en ambas aproximaciones',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 6 - Señalización vertical',
        detalle: 'Señal de CRUCE PEATONAL (R-16) colocada en ambas aproximaciones del cruce.',
      },
      {
        parametro: 'Demarcación retroreflectante',
        valor: 'Clase II mínimo',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Ver Sección 5 o 6 según aplique',
        detalle: 'La demarcación del cruce debe ser retroreflectante clase II mínimo; renovación cuando la reflectividad baje del umbral.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Ancho recomendado de cruce',
        valor: '4.0',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 5 - Intersecciones',
        detalle: 'Ancho recomendado para cruces en vías primarias con alto flujo peatonal.',
      },
      {
        parametro: 'Zona de espera peatonal',
        valor: '1.5',
        unidad: 'm (profundidad)',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 5 - Intersecciones',
        detalle: 'Profundidad mínima de la zona de espera en banqueta previa al cruce, libre de obstáculos.',
      },
      {
        parametro: 'Fase peatonal exclusiva en semáforo',
        valor: '7',
        unidad: 's mínimo',
        fuente: 'Manual de Dispositivos SEDATU 2014',
        referencia: 'Ver documento fuente',
        detalle: 'Tiempo mínimo de fase exclusiva peatonal en intersecciones semaforizadas principales.',
      },
      {
        parametro: 'Distancia libre de obstáculos',
        valor: '20',
        unidad: 'm de aproximación',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 5 - Intersecciones',
        detalle: 'La visibilidad del cruce no debe estar obstaculizada en al menos 20 m antes del cruce.',
      },
      {
        parametro: 'Cruce elevado en zonas escolares',
        valor: 'Recomendado',
        unidad: '—',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 5 - Intersecciones',
        detalle: 'Cruce peatonal elevado al nivel de banqueta recomendado frente a escuelas, hospitales y mercados para reducir velocidades.',
      },
      {
        parametro: 'Línea de detención vehicular',
        valor: '1.5',
        unidad: 'm antes del cruce',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 5 - Intersecciones',
        detalle: 'La línea de alto vehicular debe ubicarse al menos 1.5 m antes del inicio de la franja peatonal.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho óptimo de cruce',
        valor: '4.5',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Pedestrian Crossings',
        detalle: 'Ancho óptimo para alta demanda peatonal; 4.5 m permite el paso simultáneo de flujos bidireccionales.',
      },
      {
        parametro: 'Velocidad peatonal de diseño',
        valor: '1.0',
        unidad: 'm/s',
        fuente: 'NACTO / HCM 7th Ed.',
        referencia: 'Ver documento fuente',
        detalle: 'Velocidad de diseño estándar; se usa 0.9 m/s para mayor inclusión de personas mayores.',
      },
      {
        parametro: 'Triángulo de visibilidad en esquina',
        valor: '2.0 × 2.0',
        unidad: 'm',
        fuente: 'CROW Design Manual',
        referencia: 'Capítulo 6',
        detalle: 'Triángulo libre de obstáculos en esquinas para garantizar visibilidad mutua entre peatón y conductor.',
      },
      {
        parametro: 'Iluminancia mínima en cruce',
        valor: '50',
        unidad: 'lux',
        fuente: 'ITDP Estándar de Infraestructura',
        referencia: 'Módulo 3',
        detalle: 'Nivel de iluminancia promedio mínimo sobre la superficie del cruce durante horas nocturnas.',
      },
      {
        parametro: 'Extensión de banqueta en cruce',
        valor: '2.0',
        unidad: 'm mín.',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Curb Extensions',
        detalle: 'Saliente de banqueta (curb extension) de al menos 2 m para reducir la distancia de cruce y mejorar visibilidad.',
      },
      {
        parametro: 'Señal de cuenta regresiva peatonal',
        valor: 'Recomendada',
        unidad: '—',
        fuente: 'CROW Design Manual',
        referencia: 'Capítulo 6',
        detalle: 'Temporizador visual de cuenta regresiva en semáforos peatonales reduce conflictos y mejora cumplimiento.',
      },
    ],
    chartData: [
      { label: 'RCDF (mín.)', value: 3.0, unit: 'm', color: '#d97706' },
      { label: 'Manual CDMX', value: 4.0, unit: 'm', color: '#3b82f6' },
      { label: 'NACTO', value: 4.5, unit: 'm', color: '#10b981' },
    ],
    chartTitle: 'Ancho de cruce peatonal (m) — comparativa',
  },

  'ciclovia': {
    nombre: 'Ciclovía',
    descripcion: 'Infraestructura ciclista segregada del tránsito vehicular para circulación segura de bicicletas en vía pública.',
    requiereEspecialista: false,
    especialistas: [],
    nota: '',
    obligatorias: [
      {
        parametro: 'Ancho mínimo carril unidireccional',
        valor: '1.5',
        unidad: 'm',
        fuente: 'RCDF Art. 77',
        referencia: 'Art. 77, Título Quinto',
        detalle: 'Ancho libre mínimo por carril de circulación ciclista en vía exclusiva unidireccional.',
      },
      {
        parametro: 'Ancho mínimo vía ciclista exclusiva unidireccional',
        valor: '1.5',
        unidad: 'm',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 7 - Infraestructura ciclista',
        detalle: 'Ancho mínimo obligatorio para vía ciclista exclusiva unidireccional conforme a norma oficial mexicana.',
      },
      {
        parametro: 'Velocidad de diseño máxima en vía terciaria',
        valor: '30',
        unidad: 'km/h',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 5.6.3 - Vías terciarias',
        detalle: 'Velocidad máxima de diseño en vías terciarias donde se ubican las ciclovías de menor jerarquía.',
      },
      {
        parametro: 'Señalización en pavimento',
        valor: 'Cada 50',
        unidad: 'm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.17.1 (M-15.1)',
        detalle: 'Marca de ciclopista (pictograma de bicicleta + flecha) en pintura retroreflectante cada 50 m.',
      },
      {
        parametro: 'Señal vertical de ciclopista',
        valor: 'En inicio, cruces y cambios de dirección',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 6 - Señalización vertical',
        detalle: 'Señal vertical de ciclovía obligatoria al inicio y en cada cruce o cambio de alineación.',
      },
      {
        parametro: 'Delimitación lateral',
        valor: 'Franja de 30 cm o bordillo',
        unidad: '—',
        fuente: 'RCDF Art. 77',
        referencia: 'Art. 77, Título Quinto',
        detalle: 'Separación física o pintada obligatoria entre el carril ciclista y el carril vehicular adyacente.',
      },
      {
        parametro: 'Color de contraste en cruces vehiculares',
        valor: 'Verde o rojo retroreflectante',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.17.5 (M-15.5)',
        detalle: 'Color de contraste obligatorio en la zona de cruce entre ciclovía y accesos vehiculares para alertar a conductores.',
      },
      {
        parametro: 'Ancho libre mínimo sin obstáculos',
        valor: '2.5',
        unidad: 'm',
        fuente: 'RCDF Art. 77',
        referencia: 'Art. 77, Título Quinto',
        detalle: 'Espacio libre lateral mínimo entre el borde del carril ciclista y cualquier obstáculo fijo (poste, árbol, paramento).',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Ancho carril bidireccional',
        valor: '2.5',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Ancho mínimo para ciclovía bidireccional que permite cruce de dos ciclistas.',
      },
      {
        parametro: 'Separación de tráfico vehicular',
        valor: '0.5',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Anchura mínima de franja pintada o bordillo de separación entre el carril ciclista y el vehicular.',
      },
      {
        parametro: 'Velocidad de diseño',
        valor: '25',
        unidad: 'km/h',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 7 - Infraestructura ciclista',
        detalle: 'Velocidad de diseño para ciclovías urbanas en zonas de velocidad moderada.',
      },
      {
        parametro: 'Pendiente longitudinal máxima',
        valor: '5',
        unidad: '%',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Pendiente máxima recomendada; se acepta hasta 8 % en tramos cortos menores a 50 m.',
      },
      {
        parametro: 'Iluminación nocturna en ciclovía',
        valor: '10',
        unidad: 'lux mín.',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Nivel mínimo de iluminancia en el plano de rodadura de la ciclovía para garantizar seguridad nocturna.',
      },
      {
        parametro: 'Ancho de carril ciclista en intersección',
        valor: '2.0',
        unidad: 'm',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 7 - Infraestructura ciclista',
        detalle: 'Ancho mínimo del carril ciclista al atravesar intersecciones, marcado con color de contraste.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho mínimo carril unidireccional',
        valor: '1.8',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Bike Lanes',
        detalle: 'Ancho mínimo recomendado por NACTO para carril ciclista unidireccional junto a tráfico.',
      },
      {
        parametro: 'Ancho bidireccional protegido',
        valor: '3.0–4.5',
        unidad: 'm',
        fuente: 'NACTO Protected Bike Lanes',
        referencia: 'Sección Protected Bike Lanes',
        detalle: 'Rango óptimo para ciclovía bidireccional con separación física del tráfico vehicular.',
      },
      {
        parametro: 'Buffer de protección (apertura de puertas)',
        valor: '0.75',
        unidad: 'm',
        fuente: 'ITDP Ciclociudades Manual B',
        referencia: 'Módulo B',
        detalle: 'Zona buffer mínima entre ciclovía y carril de estacionamiento vehicular.',
      },
      {
        parametro: 'Radio mínimo de curvatura a 25 km/h',
        valor: '10',
        unidad: 'm',
        fuente: 'CROW Design Manual for Bicycle Traffic',
        referencia: 'Capítulo 4',
        detalle: 'Radio de curvatura mínimo que garantiza estabilidad del ciclista a la velocidad de diseño.',
      },
      {
        parametro: 'Ancho mínimo ciclovía protegida',
        valor: '2.0',
        unidad: 'm',
        fuente: 'CROW Design Manual',
        referencia: 'Capítulo 4',
        detalle: 'Ancho mínimo por sentido en ciclovía con separación física del tráfico; permite rebasar con comodidad.',
      },
      {
        parametro: 'Color de contraste en intersecciones',
        valor: 'Verde o rojo',
        unidad: '—',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Intersection Treatments',
        detalle: 'Color de contraste en la ciclovía al cruzar intersecciones vehiculares para aumentar visibilidad del conflicto.',
      },
    ],
    chartData: [
      { label: 'RCDF (mín.)', value: 1.5, unit: 'm', color: '#d97706' },
      { label: 'NACTO (mín.)', value: 1.8, unit: 'm', color: '#10b981' },
      { label: 'CROW (rec.)', value: 2.0, unit: 'm', color: '#8b5cf6' },
      { label: 'Manual CDMX (bid.)', value: 2.5, unit: 'm', color: '#3b82f6' },
    ],
    chartTitle: 'Ancho de carril ciclista (m) — comparativa',
  },

  'banquetas': {
    nombre: 'Banquetas',
    descripcion: 'Infraestructura peatonal de acera para circulación segura y accesible de peatones en vía pública.',
    requiereEspecialista: false,
    especialistas: [],
    nota: '',
    obligatorias: [
      {
        parametro: 'Ancho mínimo zona libre peatonal',
        valor: '1.5',
        unidad: 'm',
        fuente: 'RCDF Art. 76',
        referencia: 'Art. 76, Título Quinto',
        detalle: 'Ancho libre mínimo de paso peatonal sin obstáculos como postes, árboles o rampas.',
      },
      {
        parametro: 'Pendiente transversal máxima',
        valor: '2',
        unidad: '%',
        fuente: 'RCDF Art. 76 / NOM-034',
        referencia: 'Art. 76, Título Quinto',
        detalle: 'Pendiente máxima en sentido transversal de la banqueta para garantizar accesibilidad universal.',
      },
      {
        parametro: 'Material de superficie',
        valor: 'Antiderrapante sin deformaciones > 2 cm',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Ver Sección 5 o 6 según aplique',
        detalle: 'La superficie debe ser antiderrapante y sin irregularidades mayores a 2 cm de altura.',
      },
      {
        parametro: 'Altura de guarnición',
        valor: '0.15',
        unidad: 'm',
        fuente: 'RCDF Art. 76',
        referencia: 'Art. 76, Título Quinto',
        detalle: 'Altura estándar de guarnición de concreto en la unión entre banqueta y arroyo vehicular.',
      },
      {
        parametro: 'Altura máxima de obstáculos en zona de paso',
        valor: '2.0',
        unidad: 'm',
        fuente: 'RCDF Art. 65',
        referencia: 'Art. 65, Título Quinto',
        detalle: 'Libre de obstáculos verticales en zona de circulación peatonal.',
      },
      {
        parametro: 'Ancho mínimo de banqueta en vía primaria',
        valor: '2.0',
        unidad: 'm',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 7 - Elementos de diseño peatonal',
        detalle: 'Ancho mínimo total de banqueta en vías primarias conforme a norma oficial mexicana.',
      },
      {
        parametro: 'Especificación de juntas de construcción',
        valor: 'Cada 3.0m',
        unidad: 'm',
        fuente: 'RCDF Art. 68',
        referencia: 'Art. 68, Título Quinto',
        detalle: 'Juntas de dilatación para control de agrietamiento.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Ancho total banqueta (vía primaria)',
        valor: '3.0',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Ancho mínimo total incluyendo zona de equipamiento en vialidades primarias de CDMX.',
      },
      {
        parametro: 'Zona de equipamiento urbano',
        valor: '0.6',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Franja para postes, señales, mobiliario urbano y arbolado, adyacente al arroyo vehicular.',
      },
      {
        parametro: 'Cepa mínima para arbolado',
        valor: '1.5 × 1.5',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Dimensiones mínimas de cepa para árboles de sombra en banquetas de vías primarias.',
      },
      {
        parametro: 'Señalización podotáctil',
        valor: 'Obligatoria en cambios de nivel',
        unidad: '—',
        fuente: 'SEDATU',
        referencia: 'Ver documento fuente',
        detalle: 'Franja podotáctil de advertencia y guía para personas con discapacidad visual en banquetas.',
      },
      {
        parametro: 'Franja de circulación vs franja de mobiliario',
        valor: '2.0 / 0.9',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Separación clara entre zona de paso y zona de mobiliario.',
      },
      {
        parametro: 'Criterios de reparación',
        valor: 'Sustitución si daño > 30% del área',
        unidad: '—',
        fuente: 'Manual de Mantenimiento CDMX',
        referencia: 'Ver documento fuente',
        detalle: 'No reparación puntual en daños extensos.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho mínimo zona de paso',
        valor: '2.4',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Sidewalks',
        detalle: 'Zona peatonal libre de obstáculos; 1.8 m absoluto mínimo, 2.4 m recomendado.',
      },
      {
        parametro: 'Buffer de equipamiento recomendado',
        valor: '0.9–1.8',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Sidewalks',
        detalle: 'Zona entre calzada y zona peatonal para mobiliario, arbolado y ciclovía.',
      },
      {
        parametro: 'Árbol de sombra cada',
        valor: '6–9',
        unidad: 'm',
        fuente: 'ITDP Guía de Espacio Público',
        referencia: 'Módulo 2',
        detalle: 'Espaciado entre árboles de sombra para cobertura efectiva del corredor peatonal.',
      },
      {
        parametro: 'Nivel de servicio peatonal mínimo',
        valor: 'C',
        unidad: '—',
        fuente: 'HCM 7th Edition',
        referencia: 'Ver documento fuente',
        detalle: 'LOS C garantiza flujo libre sin conflictos frecuentes.',
      },
      {
        parametro: 'Índice de caminabilidad',
        valor: '> 70 puntos',
        unidad: '—',
        fuente: 'Walk Score Methodology',
        referencia: 'Ver documento fuente',
        detalle: 'Umbral de barrio caminable en zona urbana consolidada.',
      },
      {
        parametro: 'Pendiente recomendada en rampas',
        valor: '5–6',
        unidad: '%',
        fuente: 'NACTO Global Street Design Guide',
        referencia: 'Sección Accessible Curb Ramps',
        detalle: 'Óptimo entre accesibilidad y espacio disponible.',
      },
    ],
    chartData: [
      { label: 'RCDF (zona libre)', value: 1.5, unit: 'm', color: '#d97706' },
      { label: 'NACTO (recom.)', value: 2.4, unit: 'm', color: '#10b981' },
      { label: 'Manual CDMX (total)', value: 3.0, unit: 'm', color: '#3b82f6' },
    ],
    chartTitle: 'Ancho de banqueta / zona peatonal (m) — comparativa',
  },

  'peatonalizacion': {
    nombre: 'Peatonalización de Calles',
    descripcion: 'Transformación de vialidades vehiculares en espacios predominantemente o exclusivamente peatonales.',
    requiereEspecialista: false,
    especialistas: [],
    nota: 'La peatonalización implica rediseño de flujos vehiculares adyacentes. Se recomienda consultar con la Dirección General de Vialidad antes de ejecutar.',
    obligatorias: [
      {
        parametro: 'Paso libre mínimo continuo',
        valor: '3.0',
        unidad: 'm',
        fuente: 'RCDF Art. 76',
        referencia: 'Art. 76, Título Quinto',
        detalle: 'Ancho mínimo de paso libre sin obstáculos a lo largo de toda la calle peatonalizada.',
      },
      {
        parametro: 'Acceso para vehículos de emergencia',
        valor: 'Garantizado (3.0 m)',
        unidad: 'm',
        fuente: 'RCDF / Ley de Protección Civil CDMX',
        referencia: 'Art. 76, Título Quinto',
        detalle: 'Toda calle peatonalizada debe permitir el acceso de ambulancias y bomberos.',
      },
      {
        parametro: 'Señalización de restricción vehicular',
        valor: 'Obligatoria en cada acceso',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 6.3 - Señales restrictivas (R-1-1)',
        detalle: 'Señal de calle peatonal y restricción vehicular al inicio de cada acceso a la zona.',
      },
      {
        parametro: 'Señalización de restricción vehicular (accesos)',
        valor: 'Obligatoria en todos los accesos',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 6.3 - Señales restrictivas (R-1-1)',
        detalle: 'Señal R-1 y marcas en pavimento en cada entrada.',
      },
      {
        parametro: 'Velocidad máxima permitida en calle peatonal',
        valor: '30',
        unidad: 'km/h',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 5.6.3 - Vías terciarias/peatonales',
        detalle: 'Velocidad máxima permitida en vías de acceso local y calles peatonalizadas.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Superficie peatonal mínima',
        valor: '50',
        unidad: '% de la sección',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 4 - Tipos de Calles',
        detalle: 'Al menos el 50 % de la sección transversal debe destinarse a circulación peatonal.',
      },
      {
        parametro: 'Frecuencia de arbolado',
        valor: 'Cada 6',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 4 - Tipos de Calles',
        detalle: 'Plantación de árboles cada 6 m para provisión de sombra en zonas peatonalizadas.',
      },
      {
        parametro: 'Iluminación promedio mínima',
        valor: '20',
        unidad: 'lux',
        fuente: 'NOM-013-ENER',
        referencia: 'Ver documento fuente',
        detalle: 'Nivel de iluminancia promedio mínimo en la superficie de calles peatonalizadas.',
      },
      {
        parametro: 'Criterios de selección de calle candidata',
        valor: 'Volumen < 3,000 veh/día',
        unidad: 'veh/día',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 4 - Tipos de Calles',
        detalle: 'Umbral de volumen vehicular para factibilidad.',
      },
      {
        parametro: 'Mobiliario urbano mínimo por tramo',
        valor: '1 banca + 1 árbol cada 20m',
        unidad: '—',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 4 - Tipos de Calles',
        detalle: 'Activación del espacio peatonalizado.',
      },
      {
        parametro: 'Integración de vegetación',
        valor: 'Mínimo 30% de superficie permeable',
        unidad: '%',
        fuente: 'Guía para el Diseño de Espacios Públicos Seguros — SEGOB 2019',
        referencia: 'Ver documento en: generaconocimiento.segob.gob.mx',
        detalle: 'Para control de escorrentía e isla de calor.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho zona peatonal activa',
        valor: '4.5',
        unidad: 'm mínimo',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Pedestrian-Priority Streets',
        detalle: 'Ancho mínimo de la zona de tránsito activo en calles peatonalizadas de alta demanda.',
      },
      {
        parametro: 'Nodos de actividad urbana',
        valor: 'Cada ~15',
        unidad: 'm',
        fuente: 'ITDP Guía de Espacio Público',
        referencia: 'Módulo 2',
        detalle: 'Bancas, fuentes o arte urbano cada ~15 m para generar vida urbana activa en la calle.',
      },
      {
        parametro: 'Superficie permeable recomendada',
        valor: '30',
        unidad: '% mínimo',
        fuente: 'CROW Design Manual',
        referencia: 'Capítulo 7',
        detalle: 'Proporción mínima de superficie permeable para gestión de agua pluvial en sitio.',
      },
      {
        parametro: 'Indicadores de éxito post-implementación',
        valor: 'Aumento > 20% de peatones',
        unidad: '%',
        fuente: 'ITDP Pedestrian Design Guide',
        referencia: 'Módulo 4',
        detalle: 'Métrica de evaluación a 6 meses de operación.',
      },
      {
        parametro: 'Estándares de animación urbana',
        valor: 'Usos activos cada 15m de fachada',
        unidad: 'm',
        fuente: 'Project for Public Spaces',
        referencia: 'Ver documento fuente',
        detalle: 'Para garantizar vitalidad urbana continua.',
      },
    ],
    chartData: [
      { label: 'RCDF (paso mín.)', value: 3.0, unit: 'm', color: '#d97706' },
      { label: 'Manual CDMX', value: 4.0, unit: 'm', color: '#3b82f6' },
      { label: 'NACTO (activo)', value: 4.5, unit: 'm', color: '#10b981' },
    ],
    chartTitle: 'Ancho de zona peatonal (m) — comparativa',
  },

  'transporte-publico': {
    nombre: 'Integración de Transporte Público',
    descripcion: 'Diseño de infraestructura para integración modal y accesibilidad del transporte público colectivo.',
    requiereEspecialista: true,
    especialistas: ['ingeniero de tránsito', 'especialista en movilidad'],
    nota: 'El diseño de corredores de transporte público requiere análisis de demanda, modelación de flujos y coordinación con operadores del sistema.',
    obligatorias: [
      {
        parametro: 'Radio máximo de cobertura de parada',
        valor: '400',
        unidad: 'm',
        fuente: 'RCDF / Programa Movilidad CDMX',
        referencia: 'Ver documento fuente',
        detalle: 'Radio máximo de cobertura peatonal hacia paradas del sistema de transporte público.',
      },
      {
        parametro: 'Señalización de ruta en parada',
        valor: 'Obligatoria',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 6 - Señalización vertical',
        detalle: 'Identificación de rutas, destinos y frecuencias obligatoria en todas las paradas.',
      },
      {
        parametro: 'Distancia máxima entre paradas en zona urbana',
        valor: '400',
        unidad: 'm',
        fuente: 'Ley General de Movilidad Art. 46',
        referencia: 'Art. 46',
        detalle: 'Distancia máxima caminable entre paradas en zona urbana consolidada.',
      },
      {
        parametro: 'Ancho mínimo de carril exclusivo de autobús',
        valor: '3.5',
        unidad: 'm',
        fuente: 'Manual SCT / NTCVIAL CDMX',
        referencia: 'Ver documento fuente',
        detalle: 'Carril de uso exclusivo para autobús en vía primaria.',
      },
      {
        parametro: 'Radio mínimo de giro en terminal',
        valor: '15.0',
        unidad: 'm',
        fuente: 'Manual SCT',
        referencia: 'Ver documento fuente',
        detalle: 'Para vehículo de diseño articulado de 18m.',
      },
      {
        parametro: 'Señalización de carril exclusivo',
        valor: 'Obligatoria cada 50m',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.13.2 (M-11.2)',
        detalle: 'Marca en pavimento + señal vertical R-26.',
      },
      {
        parametro: 'Altura de plataforma de abordaje',
        valor: '0.25–0.32',
        unidad: 'm',
        fuente: 'RCDF / Lineamientos CDMX',
        referencia: 'Ver documento fuente',
        detalle: 'Altura sobre nivel de arroyo para abordaje a nivel.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Separación entre paradas',
        valor: '300–500',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 6 - Transporte Público',
        detalle: 'Distancia entre paradas en zona urbana densa; hasta 800 m en zonas de baja densidad.',
      },
      {
        parametro: 'Integración tarifaria multimodal',
        valor: 'Recomendada',
        unidad: '—',
        fuente: 'SEDATU Plan de Movilidad 2019',
        referencia: 'Ver documento fuente',
        detalle: 'Sistema unificado de pago con transbordos gratuitos o subsidiados entre modos.',
      },
      {
        parametro: 'Área de intercambio modal',
        valor: '50',
        unidad: 'm² mínimo',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 6 - Transporte Público',
        detalle: 'Superficie mínima en nodos de alta confluencia de rutas de transporte.',
      },
      {
        parametro: 'Frecuencia máxima de servicio recomendada',
        valor: '10',
        unidad: 'min',
        fuente: 'Guía DOTS SEDATU',
        referencia: 'Ver documento fuente',
        detalle: 'En hora pico para corredores de alta demanda.',
      },
    ],
    internacionales: [
      {
        parametro: 'Frecuencia máxima hora pico',
        valor: '10',
        unidad: 'min entre unidades',
        fuente: 'ITDP BRT Standard 2016',
        referencia: 'Módulo 3',
        detalle: 'Frecuencia máxima de paso aceptable en hora pico para un servicio de calidad.',
      },
      {
        parametro: 'Radio de cobertura peatonal',
        valor: '500',
        unidad: 'm',
        fuente: 'NACTO Transit Street Design Guide',
        referencia: 'Sección Transit Access',
        detalle: 'Radio de cobertura peatonal estándar para paradas de BRT y líneas troncales.',
      },
      {
        parametro: 'Desnivel máx. plataforma-vehículo',
        valor: '50',
        unidad: 'mm',
        fuente: 'CROW ASVV',
        referencia: 'Capítulo 8',
        detalle: 'Desnivel máximo entre plataforma de parada y piso del vehículo para acceso sin asistencia.',
      },
      {
        parametro: 'Estándar BRT para carriles exclusivos',
        valor: '3.5',
        unidad: 'm',
        fuente: 'ITDP BRT Standard',
        referencia: 'Módulo 2',
        detalle: 'Ancho mínimo carril BRT de bronce a platino.',
      },
      {
        parametro: 'Tiempo máximo de espera recomendado',
        valor: '5',
        unidad: 'min',
        fuente: 'NACTO Transit Street Design Guide',
        referencia: 'Sección Transit Access',
        detalle: 'En corredores de alta frecuencia urbana.',
      },
    ],
    chartData: [
      { label: 'RCDF (cobertura)', value: 400, unit: 'm', color: '#d97706' },
      { label: 'Manual CDMX (sep. mín.)', value: 300, unit: 'm', color: '#3b82f6' },
      { label: 'NACTO (cobertura)', value: 500, unit: 'm', color: '#10b981' },
    ],
    chartTitle: 'Radio de cobertura / separación de paradas (m) — comparativa',
  },

  'intersecciones': {
    nombre: 'Intersecciones Viales',
    descripcion: 'Diseño de puntos de confluencia entre vialidades para mayor seguridad peatonal, ciclista y vehicular.',
    requiereEspecialista: true,
    especialistas: ['ingeniero vial', 'ingeniero de tránsito'],
    nota: 'El rediseño de intersecciones requiere estudios de origen-destino, aforos vehiculares y peatonales, y análisis de siniestralidad.',
    obligatorias: [
      {
        parametro: 'Radio de giro máximo en esquina',
        valor: '6.0',
        unidad: 'm',
        fuente: 'Manual SCT',
        referencia: 'Ver documento fuente',
        detalle: 'Radio máximo de curvatura en esquinas para limitar la velocidad de giro de vehículos.',
      },
      {
        parametro: 'Triángulo de visibilidad libre',
        valor: '30 × 30',
        unidad: 'm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Ver Sección 5 o 6 según aplique',
        detalle: 'Triángulo libre de obstáculos en aproximaciones a intersecciones no semaforizadas.',
      },
      {
        parametro: 'Señalización de prioridad',
        valor: 'ALTO (R-1) o CEDA (R-2)',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 6.3 - Señales restrictivas (R-1-1)',
        detalle: 'Señal de prioridad vial obligatoria en toda intersección no semaforizada.',
      },
      {
        parametro: 'Distancia mínima de señal preventiva',
        valor: '50–100',
        unidad: 'm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 6.2 - Señales preventivas',
        detalle: 'Según velocidad de operación de la vía.',
      },
      {
        parametro: 'Señalización en intersección de 4 accesos',
        valor: 'ALTO en vías secundarias',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 6.3 - Señales restrictivas (R-1-1)',
        detalle: 'Señal R-1-1 obligatoria en vías que ceden el paso.',
      },
      {
        parametro: 'Nivel de servicio mínimo aceptable',
        valor: 'D',
        unidad: '—',
        fuente: 'Manual SCT',
        referencia: 'Ver documento fuente',
        detalle: 'LOS D máximo aceptable en hora pico en zona urbana.',
      },
      {
        parametro: 'Jerarquía de movilidad en diseño de intersección',
        valor: 'Peatón > Ciclista > TP > Vehículo particular',
        unidad: '—',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 4 - Jerarquía de movilidad',
        detalle: 'Orden de prioridad obligatorio para el diseño de intersecciones urbanas conforme a norma.',
      },
      {
        parametro: 'Velocidad máxima en vía secundaria urbana',
        valor: '30',
        unidad: 'km/h',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 5.6.2 - Vías secundarias',
        detalle: 'Velocidad máxima de operación en vías secundarias urbanas que confluyen en intersecciones.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Radio de giro recomendado',
        valor: '4.0–6.0',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 5 - Intersecciones',
        detalle: 'Rango de radio de curvatura según jerarquía vial; menor radio aumenta protección peatonal.',
      },
      {
        parametro: 'Ancho mínimo isla de refugio peatonal',
        valor: '1.8',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 5 - Intersecciones',
        detalle: 'Ancho mínimo de isla de refugio peatonal en cruces de vialidades de 4 o más carriles.',
      },
      {
        parametro: 'Diseño de isla canalizadora',
        valor: 'Área mínima 4.5 m²',
        unidad: 'm²',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 5 - Intersecciones',
        detalle: 'Para separación de movimientos conflictivos.',
      },
    ],
    internacionales: [
      {
        parametro: 'Radio de giro óptimo (peatonal)',
        valor: '3.0–4.5',
        unidad: 'm',
        fuente: 'NACTO Intersection Design Guide',
        referencia: 'Sección Intersection Design',
        detalle: 'Radio óptimo para reducir velocidades de giro y aumentar seguridad de peatones.',
      },
      {
        parametro: 'Ancho mínimo isla de refugio',
        valor: '2.0',
        unidad: 'm',
        fuente: 'NACTO Intersection Design Guide',
        referencia: 'Sección Intersection Design',
        detalle: 'Ancho mínimo de isla de refugio peatonal recomendado para seguridad en cruces amplios.',
      },
      {
        parametro: 'Avance de línea de parada ciclista',
        valor: '1.0–2.0',
        unidad: 'm',
        fuente: 'ITDP Ciclociudades',
        referencia: 'Módulo B',
        detalle: 'Avance de la línea de parada para ciclistas respecto a vehículos en semáforos.',
      },
      {
        parametro: 'Velocidad objetivo en giro',
        valor: '15–25',
        unidad: 'km/h',
        fuente: 'CROW Design Manual',
        referencia: 'Capítulo 6',
        detalle: 'Velocidad de diseño en giro para garantizar seguridad peatonal y ciclista.',
      },
      {
        parametro: 'Intersección compacta',
        valor: 'Radio de esquina 3–5m',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Intersection Design',
        detalle: 'Reduce velocidad de giro y protege al peatón.',
      },
    ],
    chartData: [
      { label: 'Manual SCT (máx.)', value: 6.0, unit: 'm', color: '#d97706' },
      { label: 'Manual CDMX (rec.)', value: 4.0, unit: 'm', color: '#3b82f6' },
      { label: 'NACTO (óptimo)', value: 3.5, unit: 'm', color: '#10b981' },
      { label: 'CROW', value: 4.0, unit: 'm', color: '#8b5cf6' },
    ],
    chartTitle: 'Radio de giro en esquina (m) — menor valor = mayor seguridad peatonal',
  },

  'jardines-infiltracion': {
    nombre: 'Jardines de Infiltración',
    descripcion: 'Infraestructura verde para captación y filtración natural de agua pluvial en vía pública.',
    requiereEspecialista: true,
    especialistas: ['hidrólogo', 'paisajista', 'ingeniero ambiental'],
    nota: 'El dimensionamiento requiere estudio de permeabilidad de suelos, análisis hidrológico de la cuenca y selección de especies adaptadas al contexto local.',
    obligatorias: [
      {
        parametro: 'Pendiente máxima de la superficie',
        valor: '5',
        unidad: '%',
        fuente: 'RCDF',
        referencia: 'Ver documento fuente',
        detalle: 'Pendiente máxima de la superficie del jardín para garantizar captación uniforme de agua.',
      },
      {
        parametro: 'Distancia mínima a cimentaciones',
        valor: '3.0',
        unidad: 'm',
        fuente: 'RCDF Art. 169',
        referencia: 'Art. 169, Título Quinto',
        detalle: 'Separación mínima entre el borde del jardín y cualquier cimentación adyacente.',
      },
      {
        parametro: 'Desborde hacia drenaje convencional',
        valor: 'Obligatorio',
        unidad: '—',
        fuente: 'RCDF',
        referencia: 'Ver documento fuente',
        detalle: 'El jardín debe contar con desborde conectado al drenaje para eventos extremos.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Capacidad de infiltración mínima',
        valor: '25',
        unidad: 'mm/hr',
        fuente: 'SEDATU Manual de Infraestructura Verde 2020',
        referencia: 'Sección 4',
        detalle: 'Tasa de infiltración mínima del sustrato medida in situ con permeámetro de campo.',
      },
      {
        parametro: 'Profundidad de sustrato drenante',
        valor: '0.3–0.6',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 7 - Infraestructura Verde',
        detalle: 'Profundidad de mezcla de sustrato de alta permeabilidad en el jardín de infiltración.',
      },
      {
        parametro: 'Relación área jardín/cuenca aportante',
        valor: '1:20',
        unidad: 'ratio',
        fuente: 'SEDATU Manual de Infraestructura Verde',
        referencia: 'Sección 4',
        detalle: 'Relación mínima entre área del jardín y área de cuenca para diseño efectivo.',
      },
      {
        parametro: 'Especies recomendadas para zonas de inundación temporal',
        valor: 'Tepozán (Buddleja cordata), Aile (Alnus acuminata), Trueno (Ligustrum lucidum)',
        unidad: '—',
        fuente: 'Manual de Plantación Urbana — SEDEMA CDMX',
        referencia: 'Anexo de especies tolerantes a humedad',
        detalle: 'Especies nativas y adaptadas tolerantes a inundación temporal recomendadas para jardines de infiltración en CDMX.',
      },
      {
        parametro: 'Distancia mínima de plantación a infraestructura',
        valor: '1.5',
        unidad: 'm',
        fuente: 'Manual de Plantación Urbana — SEDEMA CDMX',
        referencia: 'Cap. 3 - Criterios de plantación',
        detalle: 'Separación mínima entre árboles o arbustos y cualquier infraestructura subterránea o superficial.',
      },
    ],
    internacionales: [
      {
        parametro: 'Relación área/cuenca recomendada',
        valor: '1:20–1:30',
        unidad: 'ratio',
        fuente: 'NACTO Urban Street Stormwater Guide',
        referencia: 'Sección Green Infrastructure',
        detalle: 'Rango óptimo de relación jardín/cuenca para manejo efectivo de aguas pluviales.',
      },
      {
        parametro: 'Período de retorno de diseño',
        valor: '10',
        unidad: 'años',
        fuente: 'CROW Design Manual',
        referencia: 'Capítulo 7',
        detalle: 'Período de retorno de lluvia de diseño para dimensionamiento de la capacidad del jardín.',
      },
      {
        parametro: 'Green infrastructure standards',
        valor: 'Reducción de escorrentía 70–90%',
        unidad: '%',
        fuente: 'EPA Stormwater Management',
        referencia: 'Sección 3',
        detalle: 'Con mantenimiento adecuado en clima semiárido.',
      },
      {
        parametro: 'Certificación LEED',
        valor: '1–4 puntos SS crédito 6',
        unidad: 'puntos',
        fuente: 'USGBC LEED v4',
        referencia: 'Ver documento fuente',
        detalle: 'Gestión de aguas pluviales en sitio.',
      },
    ],
    chartData: [
      { label: 'Infiltración mín. (SEDATU)', value: 25, unit: 'mm/hr', color: '#d97706' },
      { label: 'Infiltración rec. (CROW)', value: 50, unit: 'mm/hr', color: '#8b5cf6' },
      { label: 'Infiltración ópt. (NACTO)', value: 75, unit: 'mm/hr', color: '#10b981' },
    ],
    chartTitle: 'Tasa de infiltración recomendada (mm/hr) — comparativa',
  },

  'estacionamiento': {
    nombre: 'Estacionamiento Público en Vía',
    descripcion: 'Diseño y regulación de cajones de estacionamiento sobre el arroyo vehicular o banqueta.',
    requiereEspecialista: false,
    especialistas: [],
    nota: '',
    obligatorias: [
      {
        parametro: 'Cajón perpendicular (ancho × largo)',
        valor: '2.5 × 5.0',
        unidad: 'm',
        fuente: 'RCDF Art. 83',
        referencia: 'Art. 83, Título Quinto',
        detalle: 'Dimensiones mínimas de cajón en ángulo de 90° respecto a la banqueta.',
      },
      {
        parametro: 'Cajón paralelo (ancho × largo)',
        valor: '2.2 × 6.0',
        unidad: 'm',
        fuente: 'RCDF Art. 83',
        referencia: 'Art. 83, Título Quinto',
        detalle: 'Dimensiones mínimas de cajón de estacionamiento paralelo a la banqueta.',
      },
      {
        parametro: 'Cajón accesible (ancho × largo)',
        valor: '3.8 × 5.0',
        unidad: 'm',
        fuente: 'RCDF Art. 83',
        referencia: 'Art. 83, Título Quinto',
        detalle: 'Dimensiones del cajón accesible para personas con discapacidad; mínimo 2 % del total.',
      },
      {
        parametro: 'Proporción cajones accesibles',
        valor: '2',
        unidad: '% del total (mín. 1)',
        fuente: 'Ley de Accesibilidad CDMX Art. 9',
        referencia: 'Art. 9',
        detalle: 'Mínimo 2 % de cajones accesibles, marcados y adyacentes a la banqueta.',
      },
      {
        parametro: 'Distancia mínima a esquina',
        valor: '10.0',
        unidad: 'm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.12, párr. 4',
        detalle: 'Para preservar visibilidad en crucero.',
      },
      {
        parametro: 'Distancia mínima a entrada de cochera',
        valor: '3.0',
        unidad: 'm',
        fuente: 'RCDF Art. 78',
        referencia: 'Art. 78, Título Quinto',
        detalle: 'Para no obstruir acceso vehicular privado.',
      },
      {
        parametro: 'Señalización horizontal y vertical',
        valor: 'Obligatoria',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.12 (M-10)',
        detalle: 'Marca E-26 en pavimento + señal vertical indicativa.',
      },
      {
        parametro: 'Restricción en zona de parada de TP',
        valor: 'Prohibido en 15m',
        unidad: 'm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.14.1 (M-12.1)',
        detalle: 'Zona de ascenso/descenso libre frente a parada.',
      },
      {
        parametro: 'Cajón perpendicular mínimo',
        valor: '2.5 x 5.0',
        unidad: 'm',
        fuente: 'RCDF Art. 80',
        referencia: 'Art. 80, Título Quinto',
        detalle: 'Dimensión mínima para auto particular.',
      },
      {
        parametro: 'Cajón paralelo mínimo',
        valor: '2.2 x 6.0',
        unidad: 'm',
        fuente: 'RCDF Art. 80',
        referencia: 'Art. 80, Título Quinto',
        detalle: 'Dimensión mínima para estacionamiento en cordón.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Restricción en vialidades primarias',
        valor: 'Prohibido',
        unidad: '—',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Estacionamiento en vía pública prohibido en vialidades primarias y arteriales de CDMX.',
      },
      {
        parametro: 'Separación de banqueta (guarnición)',
        valor: '0.15',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Altura de guarnición que separa los cajones de estacionamiento de la banqueta.',
      },
      {
        parametro: 'Señalización vertical',
        valor: 'Serie E-27 a E-29',
        unidad: '—',
        fuente: 'Manual de Dispositivos SEDATU',
        referencia: 'Sección 5',
        detalle: 'Señales de estacionamiento, restricción y zona de carga y descarga según norma SEDATU.',
      },
      {
        parametro: 'Criterios para conversión a carril ciclista',
        valor: 'Ocupación < 40% en hora pico',
        unidad: '%',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Umbral para justificar reasignación de espacio.',
      },
    ],
    internacionales: [
      {
        parametro: 'Buffer de protección ciclista',
        valor: '0.5',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Parking',
        detalle: 'Zona de amortiguamiento entre cajones y ciclovía adyacente para apertura segura de puertas.',
      },
      {
        parametro: 'Reducción máx. en zonas peatonales',
        valor: '20',
        unidad: '% de cajones actuales',
        fuente: 'ITDP Guía de Estacionamiento',
        referencia: 'Módulo 3',
        detalle: 'Reducción máxima recomendada de cajones en vía en áreas de alta peatonalización.',
      },
      {
        parametro: 'Límite de carriles con estacionamiento',
        valor: '1',
        unidad: 'carril en vía < 4 carriles',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Parking',
        detalle: 'En vialidades con menos de 4 carriles el estacionamiento en vía no debe ocupar más de 1.',
      },
      {
        parametro: 'Gestión de estacionamiento',
        valor: 'Precio dinámico por demanda',
        unidad: '—',
        fuente: 'ITDP Parking Management',
        referencia: 'Módulo 4',
        detalle: 'Herramienta para reducir cruceros en busca de lugar.',
      },
    ],
    chartData: [
      { label: 'Cajón paralelo (ancho)', value: 2.2, unit: 'm', color: '#3b82f6' },
      { label: 'Cajón perpendicular (ancho)', value: 2.5, unit: 'm', color: '#d97706' },
      { label: 'Cajón accesible (ancho)', value: 3.8, unit: 'm', color: '#10b981' },
    ],
    chartTitle: 'Ancho de cajones de estacionamiento (m) — comparativa',
  },

  'paradas-transporte': {
    nombre: 'Paradas de Transporte Público',
    descripcion: 'Diseño de paradas, bahías y refugios para usuarios del transporte público colectivo urbano.',
    requiereEspecialista: false,
    especialistas: [],
    nota: '',
    obligatorias: [
      {
        parametro: 'Longitud mínima de bahía',
        valor: '18',
        unidad: 'm',
        fuente: 'RCDF',
        referencia: 'Ver documento fuente',
        detalle: 'Longitud mínima de bahía de parada para autobús urbano estándar de 12 m.',
      },
      {
        parametro: 'Área mínima de cubierta',
        valor: '4.0',
        unidad: 'm²',
        fuente: 'RCDF Art. 67',
        referencia: 'Art. 67, Título Quinto',
        detalle: 'Cubierta mínima contra lluvia y sol en parada formal.',
      },
      {
        parametro: 'Distancia mínima a esquina',
        valor: '5.0',
        unidad: 'm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Ver Sección 5 o 6 según aplique',
        detalle: 'Para no obstruir visibilidad en crucero.',
      },
      {
        parametro: 'Iluminación mínima nocturna',
        valor: '20',
        unidad: 'lux',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 6 - Transporte Público',
        detalle: 'Nivel mínimo en zona de espera de parada.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Distancia entre paradas',
        valor: '300–500',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 6 - Transporte Público',
        detalle: 'Separación recomendada entre paradas en zona urbana densa; hasta 800 m en periferia.',
      },
      {
        parametro: 'Área de espera por usuario',
        valor: '2',
        unidad: 'm² por usuario (hora pico)',
        fuente: 'NACTO Transit Street Design Guide',
        referencia: 'Sección Bus Stops',
        detalle: 'Superficie de área de espera techada calculada para la demanda de la hora de máxima afluencia.',
      },
      {
        parametro: 'Información de rutas y horarios',
        valor: 'Obligatoria',
        unidad: '—',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 6 - Transporte Público',
        detalle: 'Mapa de red, horarios y tiempo de espera deben ser visibles en todas las paradas.',
      },
      {
        parametro: 'Iluminación en área de espera',
        valor: '50',
        unidad: 'lux mínimo',
        fuente: 'NOM-013-ENER',
        referencia: 'Ver documento fuente',
        detalle: 'Nivel de iluminancia mínimo para seguridad nocturna en el área de espera de la parada.',
      },
      {
        parametro: 'Mobiliario mínimo recomendado',
        valor: 'Banca + papelera + módulo de información',
        unidad: '—',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 6 - Transporte Público',
        detalle: 'Equipamiento básico para parada de calidad.',
      },
      {
        parametro: 'Señalización de rutas y horarios',
        valor: 'Obligatoria',
        unidad: '—',
        fuente: 'Guía DOTS SEDATU',
        referencia: 'Ver documento fuente',
        detalle: 'Mapa de red, número de ruta y frecuencia estimada.',
      },
      {
        parametro: 'Integración con cicloestacionamiento',
        valor: 'Recomendada a 5m máximo',
        unidad: '—',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 6 - Transporte Público',
        detalle: 'Al menos 4 cajones para bicicleta por parada.',
      },
      {
        parametro: 'Tipología de parada',
        valor: 'Básica / Intermedia / Alta capacidad',
        unidad: '—',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 6 - Transporte Público',
        detalle: 'La tipología de parada (básica, intermedia o de alta capacidad) debe definirse según el volumen de usuarios y el tipo de vía.',
      },
    ],
    internacionales: [
      {
        parametro: 'Desnivel máx. plataforma-vehículo',
        valor: '25',
        unidad: 'mm',
        fuente: 'CROW ASVV',
        referencia: 'Capítulo 8',
        detalle: 'Desnivel máximo entre plataforma de parada y piso del vehículo para acceso sin asistencia.',
      },
      {
        parametro: 'Longitud de plataforma BRT',
        valor: '15',
        unidad: 'm + zona buffer',
        fuente: 'NACTO Transit Street Design Guide',
        referencia: 'Sección Bus Rapid Transit',
        detalle: 'Longitud de plataforma de parada BRT más zona de amortiguamiento en los extremos.',
      },
      {
        parametro: 'Iluminancia mínima área espera',
        valor: '20',
        unidad: 'lux',
        fuente: 'ITDP BRT Standard',
        referencia: 'Módulo 3',
        detalle: 'Nivel de iluminancia mínimo en área de espera según estándar ITDP para BRT de calidad básica.',
      },
      {
        parametro: 'Estándar de cubierta en parada',
        valor: '6.0',
        unidad: 'm²',
        fuente: 'NACTO Transit Street Design Guide',
        referencia: 'Sección Bus Stops',
        detalle: 'Área óptima para 8-10 usuarios simultáneos.',
      },
      {
        parametro: 'Distancia de visibilidad para conductor',
        valor: '50',
        unidad: 'm',
        fuente: 'ITDP Pedestrian Design Guide',
        referencia: 'Módulo 4',
        detalle: 'Para detección anticipada de usuarios en parada.',
      },
    ],
    chartData: [
      { label: 'Plataforma NACTO (long.)', value: 15, unit: 'm', color: '#10b981' },
      { label: 'Bahía mín. RCDF (long.)', value: 18, unit: 'm', color: '#d97706' },
      { label: 'Sep. paradas mín. (CDMX)', value: 300, unit: 'm', color: '#3b82f6' },
    ],
    chartTitle: 'Longitud de bahía / plataforma de paradas (m) — comparativa',
  },

  'reduccion-carriles': {
    nombre: 'Reducción/Aumento de Carriles',
    descripcion: 'Modificación de la sección transversal vial mediante la reducción o adición de carriles de circulación.',
    requiereEspecialista: true,
    especialistas: ['ingeniero vial'],
    nota: 'La modificación de carriles requiere estudio de impacto vial aprobado por la Dirección General de Vialidad de la CDMX.',
    obligatorias: [
      {
        parametro: 'Ancho mínimo de carril urbano',
        valor: '3.0',
        unidad: 'm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.13 (M-11)',
        detalle: 'Ancho mínimo de carril en vialidades urbanas; 3.5 m en vías primarias de alta velocidad.',
      },
      {
        parametro: 'Longitud mínima de transición',
        valor: '60',
        unidad: 'm (a 50 km/h)',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.6 (M-4)',
        detalle: 'Longitud mínima de zona de transición al reducir o ampliar carriles a 50 km/h de velocidad diseño.',
      },
      {
        parametro: 'Señalización de zona de transición',
        valor: 'Delineadores + marcas viales + señales preventivas',
        unidad: '—',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.6 (M-4)',
        detalle: 'Señalización completa obligatoria en toda zona de reducción o ampliación de carriles.',
      },
      {
        parametro: 'Línea central doble continua',
        valor: '10',
        unidad: 'cm ancho, color amarillo',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.13 (M-11)',
        detalle: 'Línea central doble continua amarilla de 10 cm de ancho en zonas de reducción de carriles.',
      },
      {
        parametro: 'Estudio de impacto vial requerido',
        valor: 'Obligatorio si > 2 carriles afectados',
        unidad: '—',
        fuente: 'Manual SCT',
        referencia: 'Ver documento fuente',
        detalle: 'Avalado por DGV-CDMX antes de ejecución.',
      },
      {
        parametro: 'Velocidad máxima en vía primaria principal',
        valor: '50',
        unidad: 'km/h',
        fuente: 'NOM-004-SEDATU-2023 — Estructura y diseño para vías urbanas',
        referencia: 'Sección 5.6.1 - Vías primarias',
        detalle: 'Velocidad máxima permitida en vías primarias; base para el diseño de transiciones de carriles.',
      },
      {
        parametro: 'Señalización de transición',
        valor: 'Zona de transición mínima 50m',
        unidad: 'm',
        fuente: 'NOM-034-SCT2/SEDATU-2022',
        referencia: 'Sección 5.6 (M-4)',
        detalle: 'Con señales W-44 y marcas de convergencia.',
      },
    ],
    manualesNacionales: [
      {
        parametro: 'Ancho de carril recomendado',
        valor: '3.0–3.5',
        unidad: 'm',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Rango óptimo en vialidades urbanas secundarias y primarias de CDMX.',
      },
      {
        parametro: 'Velocidad de diseño en transición',
        valor: '50',
        unidad: 'km/h',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Velocidad de diseño estándar para zonas de transición de carriles en vialidades urbanas.',
      },
      {
        parametro: 'Criterios para road diet',
        valor: 'TMDA < 20,000 veh/día',
        unidad: 'veh/día',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'Umbral de volumen para reducción de 4 a 3 carriles viable.',
      },
      {
        parametro: 'Compensación con infraestructura alternativa',
        valor: 'Ciclovía o banqueta ampliada',
        unidad: '—',
        fuente: 'Manual de Calles: Diseño Vial para Ciudades Mexicanas (SEDATU/BID, 2019)',
        referencia: 'Cap. 3 - Elementos de Diseño',
        detalle: 'El espacio liberado debe reasignarse a movilidad activa.',
      },
    ],
    internacionales: [
      {
        parametro: 'Ancho mínimo carril con ciclovía',
        valor: '3.0',
        unidad: 'm',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Travel Lanes',
        detalle: 'Ancho mínimo de carril vehicular adyacente a ciclovía para garantizar seguridad.',
      },
      {
        parametro: 'Configuración "Road Diet" óptima',
        valor: '4→3 carriles',
        unidad: 'configuración',
        fuente: 'NACTO Urban Street Design Guide',
        referencia: 'Sección Road Diets',
        detalle: 'Conversión de 4 a 3 carriles con carril central de giro; mejora seguridad vial y habilita ciclovía.',
      },
      {
        parametro: 'Reducción de accidentes con road diet',
        valor: '19–47',
        unidad: '% reducción',
        fuente: 'ITDP / FHWA Road Diet Studies',
        referencia: 'Ver documento fuente',
        detalle: 'Rango documentado de reducción de accidentes en estudios de road diet en México y EE.UU.',
      },
      {
        parametro: 'Road diet methodology',
        valor: 'Reducción de accidentes 19–47%',
        unidad: '%',
        fuente: 'FHWA Road Diet Informational Guide',
        referencia: 'Ver documento fuente',
        detalle: 'Con TMDA entre 10,000 y 20,000 veh/día.',
      },
    ],
    chartData: [
      { label: 'NOM-034 (mín.)', value: 3.0, unit: 'm', color: '#d97706' },
      { label: 'NACTO (con ciclovía)', value: 3.0, unit: 'm', color: '#10b981' },
      { label: 'Manual CDMX (rec.)', value: 3.25, unit: 'm', color: '#3b82f6' },
      { label: 'NOM-034 (vía primaria)', value: 3.5, unit: 'm', color: '#8b5cf6' },
    ],
    chartTitle: 'Ancho de carril vehicular (m) — comparativa de estándares',
  },
}

export function getNormas(intervencion) {
  return normasDB[intervencion] || null
}

export function getNormasConTipoVia(intervencion, tipoVia) {
  const base = normasDB[intervencion]
  if (!base) return null
  return aplicarModificaciones(base, intervencion, tipoVia)
}
